# Generated by Django 4.1.4 on 2022-12-14 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0004_subscribe'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('qr_code', models.ImageField(upload_to='all_qr/')),
                ('qr_info', models.CharField(blank=True, max_length=200, null=True)),
                ('qr_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'qr_collections',
                'db_table': 'qr_collection',
            },
        ),
    ]
