# Generated by Django 4.1.4 on 2022-12-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0005_qrcollection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcollection',
            name='qr_code',
            field=models.ImageField(upload_to=''),
        ),
    ]
